### ISSUE TITLE
Cache size limit ?

### ISSUE THREAD

**Issue by nyl-auster** [AlbinoDrought/cachios#4]
hello ! thanks for this package, super easy to use !
i use it for https://yineo.fr and i have a few questions, regarding cache stats https://yineo.fr/api/cache

- is there a limit for the cache size ?
- is there a single cache key by uniq http request, or may the same http request be cached two times with two different cache id on certain conditions ?
- why there is some "misses" ? 

Here is my current naive implementation of cachios : 
https://github.com/nyl-auster/yineo-nuxt-wordpress/blob/master/api/proxy.js

**Comment by AlbinoDrought** [comment]
Hey,

>- is there a limit for the cache size ?

The cache is handled almost directly by[ `node-cache`](https://www.npmjs.com/package/node-cache). It doesn't seem like there is a limit, but there is a somewhat-related issue open here: https://github.com/mpneuried/nodecache/issues/76

>- is there a single cache key by uniq http request, or may the same http request be cached two times with two different cache id on certain conditions ?

The cache key is determined by the `getCacheIdentifier` function. The default one looks like this:

```js
cachios.getCacheIdentifier = function (config) {
  return {
    method: config.method,
    url: config.url,
    params: config.params,
    data: config.data,
    headers: config.headers,
  };
};
```

With the default setup, requests will be cached based on their method, url, query params, post data, and headers. The returned cache identifier is passed into [`object-hash`](https://www.npmjs.com/package/object-hash), which does the work of actually differentiating the identifiers.

>- why there is some "misses" ?

[A cache miss, generally, is when something is looked up in the cache and is not found](https://stackoverflow.com/a/18559358/3649573). When using cachios, there will probably be one "cache miss" for every cached request, so that cachios can perform the request and cache the response. This willl increase over time as cached responses expire, while the amount of cached values will stay the same.

**Comment by nyl-auster** [comment]
@AlbinoDrought thanks for this complete answer, i will take a look as soon as i can
